-- Insert 25 test notifications for user_id = 2 (msa2@msa.com)
INSERT INTO notifications (user_id, type, title, message, `read`, created_at) VALUES
(2, 'MEDICATION_REMINDER', '약 복용 알림 1', '아스피린 복용 시간입니다', 0, DATE_SUB(NOW(), INTERVAL 1 HOUR)),
(2, 'MEDICATION_REMINDER', '약 복용 알림 2', '혈압약 복용 시간입니다', 0, DATE_SUB(NOW(), INTERVAL 2 HOUR)),
(2, 'DIET_WARNING', '음식 주의 3', '와파린 복용 중 시금치 섭취 주의', 0, DATE_SUB(NOW(), INTERVAL 3 HOUR)),
(2, 'MEDICATION_REMINDER', '약 복용 알림 4', '당뇨약 복용 시간입니다', 0, DATE_SUB(NOW(), INTERVAL 4 HOUR)),
(2, 'FAMILY_EVENT', '가족 알림 5', '보호자가 복약 확인을 요청했습니다', 0, DATE_SUB(NOW(), INTERVAL 5 HOUR)),
(2, 'MEDICATION_REMINDER', '약 복용 알림 6', '콜레스테롤약 복용 시간입니다', 0, DATE_SUB(NOW(), INTERVAL 6 HOUR)),
(2, 'SYSTEM', '시스템 알림 7', '약 재고가 부족합니다', 0, DATE_SUB(NOW(), INTERVAL 7 HOUR)),
(2, 'MEDICATION_REMINDER', '약 복용 알림 8', '위장약 복용 시간입니다', 0, DATE_SUB(NOW(), INTERVAL 8 HOUR)),
(2, 'DIET_WARNING', '음식 주의 9', '자몽 주스 섭취 주의', 0, DATE_SUB(NOW(), INTERVAL 9 HOUR)),
(2, 'MEDICATION_REMINDER', '약 복용 알림 10', '진통제 복용 시간입니다', 0, DATE_SUB(NOW(), INTERVAL 10 HOUR)),
(2, 'MEDICATION_REMINDER', '약 복용 알림 11', '소화제 복용 시간입니다', 0, DATE_SUB(NOW(), INTERVAL 11 HOUR)),
(2, 'FAMILY_EVENT', '가족 알림 12', '보호자가 메시지를 보냈습니다', 0, DATE_SUB(NOW(), INTERVAL 12 HOUR)),
(2, 'MEDICATION_REMINDER', '약 복용 알림 13', '항생제 복용 시간입니다', 0, DATE_SUB(NOW(), INTERVAL 13 HOUR)),
(2, 'SYSTEM', '시스템 알림 14', '정기 검진 일정이 다가옵니다', 0, DATE_SUB(NOW(), INTERVAL 14 HOUR)),
(2, 'MEDICATION_REMINDER', '약 복용 알림 15', '영양제 복용 시간입니다', 0, DATE_SUB(NOW(), INTERVAL 15 HOUR)),
(2, 'DIET_WARNING', '음식 주의 16', '칼슘 섭취 시간 간격 유지 필요', 0, DATE_SUB(NOW(), INTERVAL 16 HOUR)),
(2, 'MEDICATION_REMINDER', '약 복용 알림 17', '수면제 복용 시간입니다', 0, DATE_SUB(NOW(), INTERVAL 17 HOUR)),
(2, 'MEDICATION_REMINDER', '약 복용 알림 18', '심장약 복용 시간입니다', 0, DATE_SUB(NOW(), INTERVAL 18 HOUR)),
(2, 'FAMILY_EVENT', '가족 알림 19', '새로운 가족 구성원이 추가되었습니다', 0, DATE_SUB(NOW(), INTERVAL 19 HOUR)),
(2, 'MEDICATION_REMINDER', '약 복용 알림 20', '갑상선약 복용 시간입니다', 0, DATE_SUB(NOW(), INTERVAL 20 HOUR)),
(2, 'SYSTEM', '시스템 알림 21', '약 유효기간이 임박합니다', 0, DATE_SUB(NOW(), INTERVAL 21 HOUR)),
(2, 'MEDICATION_REMINDER', '약 복용 알림 22', '알레르기약 복용 시간입니다', 0, DATE_SUB(NOW(), INTERVAL 22 HOUR)),
(2, 'MEDICATION_REMINDER', '약 복용 알림 23', '관절염약 복용 시간입니다', 0, DATE_SUB(NOW(), INTERVAL 23 HOUR)),
(2, 'DIET_WARNING', '음식 주의 24', '알코올 섭취 주의', 0, DATE_SUB(NOW(), INTERVAL 24 HOUR)),
(2, 'MEDICATION_REMINDER', '약 복용 알림 25', '종합비타민 복용 시간입니다', 0, DATE_SUB(NOW(), INTERVAL 25 HOUR));
